language: node_js
node_js:
- '4.1'
- '4.0'
deploy:
  provider: npm
  email: philippevoinov@gmail.com
  api_key:
    secure: lgFPLVbdcx6W+Q6GRSn1ubc2QwYHS01Cw6qjFEGy2Qmw/TX2qh/d7J/xrn4onW4pLUUDQ/ArCe28RvBLcl4NZHh1KDb4jEjC8iIoMdI3ToVUSgS/fhVt4T1fAn56QbHN3D+f8OuL3i+sGYnJ5ywWgGjmfVm64yK1Cy977TO/7Zm7QRFzrEEErRgC4ImH4fgMWOSCpUhEymNPGfjw/LyifD4RBlHQuC3BD9aeypgk+Svu8ijTH4yb37BFnSukb+g1Ya07oTWF05bsJCPhIAj735PgxJtz0uTBhWeQ7gT/Z1U9nkQJ00a9njy0jjgyoNya7Z5kAk34+jj6fKr6SAosXR0NNsgd+VeCOJpEmyKwuikkV8DdyV+tMrI68JmFF5OHSMgHURmcz1E9C+RindDTGZdk+wNAVwzVshlTZ38upWLb7kXpVLl/iJxwlsafFt33tKi8CtGip5eId33KsnLfioeYFUr0cJCGbJB8NjBYSLlnqdd6Ogn0NmrA9DMYrIhJjtcha52RUBZjcE8c0zhQMcSIQJNkdpvn2kUqY1+ecyCw/BQYMRwVyFzOjhRXdWVij7M0snCo1zuqKBS9NLAA/SeMutlFD+yNesUrBgeDHQNtAD10myNRws5hcHILv49HhWO7woLYoQgEP4CqLCu1a7Z1eDly2Mkmmz4PUL3hV8Q=
  on:
    tags: true
    repo: tehwalris/socket-io-mocks
